spring:
  application:
    name: watcher
  main:
    web-environment: false
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  rabbitmq:
    url: ${RM_RABBIT_URL}
  cloud:
    stream:
      bindings:
        output:
          producer:
            required-groups:
              - posts
          destination: ${spring.application.name}.feed
          content-type: application/json
  datasource:
    url: ${RM_DB_URL}

telegram:
  api-id: ${RM_TG_API_ID}
  api-hash: ${RM_TG_API_HASH}
  phone-number: ${RM_TG_NUMBER}
  model: Bot
  app-version: ${VERSION}
  sys-version: ${VERSION}
  lang-code: en
#  storage-path: ${java.io.tmpdir}
  storage-path: ${user.home}${file.separator}.telegram-rss-manager${file.separator}watcher

processing:
  channel-processing-delay: 2
  download-batch-size: 50
  download-concurrency: 10

logging:
  root:
    level: INFO
